// todo-React-redis/client/src/App.jsx
import "./App.css";
import TodoForm from "./components/TodoForm.jsx";
import TodoItem from "./components/TodoItem.jsx";
import { useState, useEffect } from "react";
import { fetchTodos, addTodo_request } from "./requests.js";

export default function App() {
  // state
  const [todos, setTodos] = useState([]);

  // methods
  async function addTodo(txt) {
    const newTodo = {
      txt: txt,
      checkbox: false,
      date: "",
      notes: "",
      priority: "",
    };
    await addTodo_request(newTodo);
    setTodos(await fetchTodos());
  }

  function deleteTodo(id) {
    const newTodos = todos.filter((todo) => todo.id !== id);
    window.localStorage.setItem("todos", JSON.stringify(newTodos));
    fetchTodos();
  }

  function updateTodo(id, property, value) {
    const newTodos = todos.map((todo) => {
      if (todo.id === id) {
        todo[`${property}`] = value;
        return todo;
      } else return todo;
    });
    window.localStorage.setItem("todos", JSON.stringify(newTodos));
    fetchTodos();
  }

  // useEffect
  useEffect(() => {
    fetchTodos().then((data) => {
      setTodos(data);
    });
  }, []);

  return (
    <div>
      <TodoForm addTodoProp={addTodo} />
      <div id="todoContainer">
        <div className="itemDiv">
          {todos.map((item) => {
            return (
              <TodoItem
                key={item.id}
                todoItem={item}
                deleteTodo={deleteTodo}
                updateTodo={updateTodo}
              />
            );
          })}
        </div>
      </div>
    </div>
  );
}

// todo-Vue-Mongo/client/src/App.vue
<!-- template start-->
<template>
  <ToDoForm @todoAdded="addTodo"></ToDoForm>

  <div id="todoContainer">
    <div v-for="todo in todosArr" :key="todo.id">
      <TodoItem :item =todo></TodoItem>
    </div>
  </div>

</template>

<!-- script start-->
<script>
import ToDoForm from './components/ToDoForm.vue'
import TodoItem from './components/ToDoItem.vue'

export default {
  data() {
    return {
      id: 1,
      todosArr: [
        { "id": '1', "txt": "todo1", "date": '2022-10-10', "priority": "Medium", "notes": 'notes1', "checkbox": true },
        { "id": '2', "txt": "todo2", "date": '2022-11-11', "priority": "None", "notes": 'notes2', "checkbox": true }
      ]
    }
  },

  components: { ToDoForm, TodoItem },

  methods: {
    addTodo(todoTxtInput) {
      this.id += 1
      this.todosArr.push({ 'id': this.id, 'txt': todoTxtInput })
    }
  }
}
</script>

<!-- style start-->
<style>
#todoContainer {
  font-size: 150%;
}
</style>
