// todo-React-redis/client/src/components/TodoForm.jsx
import { useState } from 'react';
import './TodoForm.css';

function TodoForm({ addTodoProp }) {
  // state
  let [todoInput, setTodoInput] = useState('');

  // methods
  function addTodo() {
    if (todoInput.length > 0) {
      addTodoProp(todoInput);
      setTodoInput('');
    }
  }

  // component return
  return (
    <div id="todoForm">
      <form onSubmit={(e) => e.preventDefault()}>
        <label id="todoLabel">ToDo</label>
        <br />
        <input
          type="text"
          className="inputTxt"
          placeholder="what needs to be done?"
          value={todoInput}
          onChange={(e) => setTodoInput(e.target.value)}
        />
        <button id="addButton" onClick={addTodo}>
          Add
        </button>
      </form>
    </div>
  );
}

export default TodoForm;

// todo-Vue-Mongo/src/components/ToDoForm.vue
<!-- template -->
<template>
    <form @submit.prevent = "submitNewTodo">
        <label><strong>To-Do</strong></label>
        <input type="text" required v-model="todoTxtInput" placeholder="what needs to be done?">
        <button>Add</button>
    </form>
</template>

<!-- script -->
<script>
export default {
    data () {
        return {
            todoTxtInput: ''
        }
    },
    methods: {
        submitNewTodo () {
            this.$emit('todoAdded', this.todoTxtInput)
            this.todoTxtInput = ''
        }
    }
}
</script>

<!-- style -->
<style>

</style>
