// todo-React-redis/client/my-app/src/components/TodoForm.jsx
import { useState } from "react";
import "./TodoForm.css";

function TodoForm() {
  // state
  let [todoInput, setTodoInput] = useState("");

  // callback methods
  function addTodo() {
    // console.log(todoInput);
    setTodoInput("");
  }

  // return
  return (
    <div id="todoForm">
      <form onSubmit={(e) => e.preventDefault()}>
        <label id="todoLabel">ToDo</label>
        <br />
        <input
          type="text"
          required
          className="inputTxt"
          placeholder="what needs to be done?"
          value={todoInput}
          onChange={(e) => setTodoInput(e.target.value)}
        />
        <button id="addButton" onClick={addTodo}>
          Add
        </button>
      </form>
    </div>
  );
}

export default TodoForm;

// todo-Vue-Mongo/src/components/ToDoForm.vue
<!-- template -->
<template>
    <form @submit.prevent = "submitNewTodo">
        <label><strong>To-Do</strong></label>
        <input type="text" required v-model="todoTxtInput" placeholder="what needs to be done?">
        <button>Add</button>
    </form>
</template>

<!-- script -->
<script>
export default {
    data () {
        return {
            todoTxtInput: ''
        }
    },
    methods: {
        submitNewTodo () {
            this.$emit('todoAdded', this.todoTxtInput)
            this.todoTxtInput = ''
        }
    }
}
</script>

<!-- style -->
<style>

</style>
