// todo-React-redis/client/my-app/src/components/TodoItem.jsx
export default function TodoItem({ item }) {
  return (
    <div className="todoItem">
      <input type="checkbox" value={item.checkbox} />
      <input type="text" value={item.txt} />
      <div className="properties">
        <textarea cols="30" rows="10" value={item.notes} />
        <label>Due Date</label>
        <input type="date" value={item.date} />
        <label>Priority</label>
        <select value={item.priority}>
          <option>None</option>
          <option>Low</option>
          <option>Medium</option>
          <option>High</option>
        </select>
        <button>Delete</button>
      </div>
    </div>
  );
}

// todo-Vue-Mongo/src/components/ToDoItem.vue
<!-- template start-->
<template>
    <div class="todoItemDiv">
        <input class="todoInput" type="checkbox">
        <input type="text">
        <div class="propertiesDiv">
            <textarea name="" id="" cols="30" rows="10"></textarea>
            <label for="">Due Date: </label>
            <input type="date">
            <label for="">priority</label>
            <select name="" id="">
                <option value="">None</option>
                <option value="">Low</option>
                <option value="">Medium</option>
                <option value="">High</option>
            </select>
            <button>Delete</button>
        </div>
    </div>
</template>

<!-- script start-->
<script>
export default {
    data() {
        return {

        }
    }
}
</script>
    
<!-- style start-->
<style>
.todoItemDiv {
    font-size: 120%;
    background-color: #C4D7E0;
    margin-left: 28%;
    margin-right: 30%;
    margin-bottom: 0.4%;
    border-radius: 14px;
}

.propertiesDiv {
    /* display: none; */

}

.todoInput {
    /* margin-bottom: 0.1%; */
}
</style>
